### ISSUE TITLE
TypeError: Cannot read property 'state' of undefined

### ISSUE THREAD

**Issue by Data0Face** [aneagoie/robofriends#2]
Hey Sorry I'm kind of new can you help me with this it can't read the property of state as it says so here is my code 

`class App extends Component{ 
    constructor(){
        super()
        this.state ={
            robots:robots,
            searchfield:''
        } 
    }
    onSearchChange(event){

        const filteredRobots= this.state.robots.filter(robot=>{
            return robots.name.toLowerCase().includes(this.state.searchfield.toLowerCase());
        })
        console.log(filteredRobots);
    }
   
    render (){  
        return(
        <div className="tc">
            <SearchBox searchChange={this.onSearchChange}/>
            <CardList robots={this.state.robots}/>
        </div>
        );
    }
 } 
export default App;`

**Comment by Data0Face** [comment]
Problem Solved Sorry

**Comment by azukaemeshili** [comment]
> Problem Solved Sorry

please how did you fix this? thanks for your help in advance
