### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by ShmidtAlex** [aneagoie/robofriends#6]
I've used this files as a basement for setup redux as it shown in tutorials, but, there is might me some misconceptions, because the purpose way isn't working. I did all as in tutorial and even download this folder and make redux setup from scratch, but there is an error with searchRobots variable. 
`typeError: Cannot read property 'searchField' of undefined
Function.mapSateToProps [as mapToProps]
src/containers/App.js:12
   9 | 
  10 | const mapSateToProps = state => {
  11 |   return {
> 12 |     searchField: state.searchRobots.searchField
  13 |   }
  14 | }`

**Comment by ShmidtAlex** [comment]
it helped me to change line 12 as:
searchField: searchRobots(state.searchField);

and importing searchRobots directly to the App.js

**Comment by evg1n** [comment]
Did you try wrapping returning values with ( ) instead of {}?

**Comment by socialmecpl** [comment]
I also have the same issue, but it is resolve with @ShmidtAlex method.

**Comment by socialmecpl** [comment]
`import {searchRobots} from '../reducers.js';

const mapStateToProps = (state) => {
	return {
		searchField: searchRobots(state.searchField)
	}
}`

try this to avoid error.

**Comment by edmondokosun** [comment]
>  searchField: searchRobots(state.searchField);

Woah, this hack worked for me. But lemme ask, why did the instructor own work and ours didn't?

My own code compiled successfully, but the error showed in the browser, and this was the error summary

**_TypeError: state.searchRobots is undefined_**

Thanks @ShmidtAlex

**Comment by Dobro47** [comment]
I cloned the project files and for some reason the shorthand 'tc' is not working for the <div className='tc'>.
Everything is stuck to the left? Anyone else having that problem?

**Comment by PeqProg** [comment]
> I cloned the project files and for some reason the shorthand 'tc' is not working for the
> 
> .
> Everything is stuck to the left? Anyone else having that problem?

Don't forget in command line: npm install tachyons
