### ISSUE TITLE
Cards are rendering with different sizes

### ISSUE THREAD

**Issue by VigneshG1616** [aneagoie/robofriends#71]
The card list component is rendering with different sizes (as per the name length). I guess we need to add some CSS to fix width of card for the card list component. please see the attachments for the clarity.
![Screenshot (42)](https://user-images.githubusercontent.com/60097654/157460934-42275b46-a851-4135-b840-9edddcf0d7f1.png)
![Screenshot (43)](https://user-images.githubusercontent.com/60097654/157461014-58608296-c24f-45f6-a34f-8e14ccda2bea.png)

**Comment by Akshatkumar4433** [comment]
So we have to make a change so all cards look same width. No matter the name length.
